block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
  "ci-linux (stable, x86_64-unknown-linux-gnu)",
  "ci-linux (stable, x86_64-unknown-linux-musl)",
  "ci-linux (beta, x86_64-unknown-linux-gnu)",
  "ci-linux (beta, x86_64-unknown-linux-musl)",
  "ci-linux (1.40.0, x86_64-unknown-linux-gnu)",
  "ci-linux (1.40.0, x86_64-unknown-linux-musl)",
]
